# 📊 EDA: Análisis de Influencia de YouTube en el Consumo

## 🎯 Objeto de Estudio
El propósito de este análisis es determinar cómo las **búsquedas y reproducciones en YouTube** impactan directamente en el consumo de productos relacionados.

---

## 🔍 Metodología y Recogida de Datos
Para este estudio, se cruzarán datos de dos fuentes clave de la infraestructura de Google para medir el interés de los usuarios:

1.  **Google Trends:** Para obtener datos sobre las **búsquedas intencionadas** y tendencias globales.
    "./searched_with_top-queries_ES_20210322-2141_20260322-2141.csv"
2.  **API de YouTube:** A través de *Google Cloud Platform*, para extraer métricas de contenido y visualizaciones.

> ### 🪵 Enfoque del Análisis
> Para aportar mayor profundidad, el estudio se focalizará específicamente en el sector del **bricolaje y la carpintería**.

---

## 🛠️ Requisitos Técnicos
Para interactuar con la API de Google desde el entorno de desarrollo, es necesario instalar el cliente oficial de Python:

```bash
pip install google-api-python-client

In [1]:
%pip install --upgrade google-api-python-client

Collecting google-api-python-client
  Downloading google_api_python_client-2.193.0-py3-none-any.whl.metadata (7.0 kB)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.31.2-py3-none-any.whl.metadata (2.2 kB)
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 (from google-api-python-client)
  Downloading google_auth-2.49.1-py3-none-any.whl.metadata (6.2 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client)
  Downloading google_auth_httplib2-0.3.0-py3-none-any.whl.metadata (3.1 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.30.0-py3-none-any.whl.metadata (3.1 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting googleapis-common-protos<2.0.0,>=1.56.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.73.0-py3-none-any.whl.metadata (9.4 kB)
Collecting protobuf<7.0.0,>=4.25.8 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.27.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in c:\users\jlalo\appdata\local\programs\python\python311\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.5)
Collecting pyasn1-modules>=0.2.1 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading cryptography-46.0.5-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\users\jlalo\appdata\local\programs\python\python311\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Collecting cffi>=2.0.0 (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading cffi-2.0.0-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jlalo\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jlalo\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jlalo\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jlalo\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.2.25)
Collecting pycparser (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Downloading google_api_python_client-2.193.0-py3-none-any.whl (14.9 MB)
   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/14.9 MB 1.3 MB/s eta 0:00:12
   ---------------------------------------- 0.2/14.9 MB 1.4 MB/s eta 0:00:11
    --------------------------------------- 0.2/14.9 MB 1.4 MB/s eta 0:00:11
    --------------------------------------- 0.3/14.9 MB 1.6 MB/s eta 0:00:10
   - -------------------------------------- 0.4/14.9 MB 1.5 MB/s eta 0:00:10
   - -------------------------------------- 0.5/14.9 MB 1.5 MB/s eta 0:00:10
   - -------------------------------------- 0.5/14.9 MB 1.4 MB/s eta 0:00:11
   - -------------------------------------- 0.5/14.9 MB 1.4 MB/s eta 0:00:11
   - -------------------------------------- 0.5/14.9 MB 1.2 MB/s eta 0:00:12
   - -------------------------------------- 0.6/14.9 MB 1.2 MB/s eta 0:00:13
   - -------------------------------------- 0.6/14.9 MB 1.2 MB/s eta 0:00:13
   - -------------------------------------- 0.7/14.9 MB 1.2 MB/s eta 0:00:13
   -- ------------------------------------- 0.7/14.9 MB 1.2 MB/s eta 0:00:12
   -- ------------------------------------- 0.8/14.9 MB 1.2 MB/s eta 0:00:13
   -- ------------------------------------- 0.8/14.9 MB 1.2 MB/s eta 0:00:13
   -- ------------------------------------- 0.9/14.9 MB 1.2 MB/s eta 0:00:12
   -- ------------------------------------- 1.0/14.9 MB 1.2 MB/s eta 0:00:12
   -- ------------------------------------- 1.0/14.9 MB 1.2 MB/s eta 0:00:12
   -- ------------------------------------- 1.1/14.9 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.1/14.9 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.2/14.9 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.2/14.9 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.3/14.9 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.3/14.9 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.4/14.9 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.5/14.9 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.5/14.9 MB 1.2 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/14.9 MB 1.2 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/14.9 MB 1.2 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/14.9 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.6/14.9 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.6/14.9 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.6/14.9 MB 1.1 MB/s eta 0:00:13
   ---- ----------------------------------- 1.7/14.9 MB 1.1 MB/s eta 0:00:13
   ---- ----------------------------------- 1.7/14.9 MB 1.1 MB/s eta 0:00:13
   ---- ----------------------------------- 1.7/14.9 MB 1.1 MB/s eta 0:00:13
   ---- ----------------------------------- 1.7/14.9 MB 1.0 MB/s eta 0:00:13
   ---- ----------------------------------- 1.7/14.9 MB 1.0 MB/s eta 0:00:13
   ---- ----------------------------------- 1.8/14.9 MB 985.7 kB/s eta 0:00:14
   ---- ----------------------------------- 1.8/14.9 MB 985.7 kB/s eta 0:00:14
   ---- ----------------------------------- 1.8/14.9 MB 985.7 kB/s eta 0:00:14
   ---- ----------------------------------- 1.8/14.9 MB 985.7 kB/s eta 0:00:14
   ---- ----------------------------------- 1.8/14.9 MB 915.3 kB/s eta 0:00:15
   ---- ----------------------------------- 1.8/14.9 MB 915.3 kB/s eta 0:00:15
   ---- ----------------------------------- 1.8/14.9 MB 877.2 kB/s eta 0:00:15
   ---- ----------------------------------- 1.8/14.9 MB 877.2 kB/s eta 0:00:15
   ---- ----------------------------------- 1.8/14.9 MB 877.2 kB/s eta 0:00:15
   ----- ---------------------------------- 1.9/14.9 MB 847.5 kB/s eta 0:00:16
   ----- ---------------------------------- 1.9/14.9 MB 847.5 kB/s eta 0:00:16
   ----- ---------------------------------- 1.9/14.9 MB 826.0 kB/s eta 0:00:16
   ----- ---------------------------------- 1.9/14.9 MB 826.0 kB/s eta 0:00:16
   ----- ---------------------------------- 1.9/14.9 MB 804.4 kB/s eta 0:00:17
   ----- ---------------------------------- 1.9/14.9 MB 804.4 kB/s eta 0:00:17
   ----- ---------------------------------- 2.0/14.9 MB 791.5 kB/s eta 0:00:17
   ----- ---------------------------------- 2.0/14.9 MB 794.6 kB/s eta 0:00:17
   ----- ---------------------------------- 2.0/14.9 MB 794.6 kB/s eta 0:00:17
   ----- ---------------------------------- 2.0/14.9 MB 777.7 kB/s eta 0:00:17
   ----- ---------------------------------- 2.0/14.9 MB 777.7 kB/s eta 0:00:17
   ----- ---------------------------------- 2.1/14.9 MB 765.3 kB/s eta 0:00:17
   ----- ---------------------------------- 2.1/14.9 MB 765.3 kB/s eta 0:00:17
   ----- ---------------------------------- 2.1/14.9 MB 753.2 kB/s eta 0:00:17
   ----- ---------------------------------- 2.1/14.9 MB 753.2 kB/s eta 0:00:17
   ----- ---------------------------------- 2.2/14.9 MB 743.5 kB/s eta 0:00:18
   ----- ---------------------------------- 2.2/14.9 MB 742.6 kB/s eta 0:00:18
   ----- ---------------------------------- 2.2/14.9 MB 730.5 kB/s eta 0:00:18
   ------ --------------------------------- 2.3/14.9 MB 739.9 kB/s eta 0:00:18
   ------ --------------------------------- 2.3/14.9 MB 731.4 kB/s eta 0:00:18
   ------ --------------------------------- 2.3/14.9 MB 736.8 kB/s eta 0:00:18
   ------ --------------------------------- 2.3/14.9 MB 736.8 kB/s eta 0:00:18
   ------ --------------------------------- 2.4/14.9 MB 728.5 kB/s eta 0:00:18
   ------ --------------------------------- 2.4/14.9 MB 728.5 kB/s eta 0:00:18
   ------ --------------------------------- 2.4/14.9 MB 726.8 kB/s eta 0:00:18
   ------ --------------------------------- 2.4/14.9 MB 716.4 kB/s eta 0:00:18
   ------ --------------------------------- 2.4/14.9 MB 712.5 kB/s eta 0:00:18
   ------ --------------------------------- 2.5/14.9 MB 711.7 kB/s eta 0:00:18
   ------ --------------------------------- 2.5/14.9 MB 711.7 kB/s eta 0:00:18
   ------ --------------------------------- 2.5/14.9 MB 710.2 kB/s eta 0:00:18
   ------ --------------------------------- 2.5/14.9 MB 710.2 kB/s eta 0:00:18
   ------ --------------------------------- 2.6/14.9 MB 705.9 kB/s eta 0:00:18
   ------- -------------------------------- 2.6/14.9 MB 713.9 kB/s eta 0:00:18
   ------- -------------------------------- 2.7/14.9 MB 713.1 kB/s eta 0:00:18
   ------- -------------------------------- 2.7/14.9 MB 713.1 kB/s eta 0:00:18
   ------- -------------------------------- 2.7/14.9 MB 709.2 kB/s eta 0:00:18
   ------- -------------------------------- 2.7/14.9 MB 708.5 kB/s eta 0:00:18
   ------- -------------------------------- 2.7/14.9 MB 708.5 kB/s eta 0:00:18
   ------- -------------------------------- 2.8/14.9 MB 699.4 kB/s eta 0:00:18
   ------- -------------------------------- 2.8/14.9 MB 699.1 kB/s eta 0:00:18
   ------- -------------------------------- 2.8/14.9 MB 695.8 kB/s eta 0:00:18
   ------- -------------------------------- 2.9/14.9 MB 695.3 kB/s eta 0:00:18
   ------- -------------------------------- 2.9/14.9 MB 695.1 kB/s eta 0:00:18
   ------- -------------------------------- 2.9/14.9 MB 699.5 kB/s eta 0:00:18
   ------- -------------------------------- 3.0/14.9 MB 696.5 kB/s eta 0:00:18
   -------- ------------------------------- 3.0/14.9 MB 703.2 kB/s eta 0:00:17
   -------- ------------------------------- 3.0/14.9 MB 705.4 kB/s eta 0:00:17
   -------- ------------------------------- 3.1/14.9 MB 707.1 kB/s eta 0:00:17
   -------- ------------------------------- 3.2/14.9 MB 715.9 kB/s eta 0:00:17
   -------- ------------------------------- 3.2/14.9 MB 713.1 kB/s eta 0:00:17
   -------- ------------------------------- 3.2/14.9 MB 713.1 kB/s eta 0:00:17
   -------- ------------------------------- 3.2/14.9 MB 707.1 kB/s eta 0:00:17
   -------- ------------------------------- 3.3/14.9 MB 709.1 kB/s eta 0:00:17
   -------- ------------------------------- 3.3/14.9 MB 709.1 kB/s eta 0:00:17
   -------- ------------------------------- 3.3/14.9 MB 703.5 kB/s eta 0:00:17
   -------- ------------------------------- 3.3/14.9 MB 703.3 kB/s eta 0:00:17
   --------- ------------------------------ 3.3/14.9 MB 700.4 kB/s eta 0:00:17
   --------- ------------------------------ 3.4/14.9 MB 708.6 kB/s eta 0:00:17
   --------- ------------------------------ 3.5/14.9 MB 708.1 kB/s eta 0:00:17
   --------- ------------------------------ 3.5/14.9 MB 713.8 kB/s eta 0:00:16
   --------- ------------------------------ 3.6/14.9 MB 719.8 kB/s eta 0:00:16
   --------- ------------------------------ 3.6/14.9 MB 723.2 kB/s eta 0:00:16
   --------- ------------------------------ 3.7/14.9 MB 730.8 kB/s eta 0:00:16
   ---------- ----------------------------- 3.7/14.9 MB 732.3 kB/s eta 0:00:16
   ---------- ----------------------------- 3.8/14.9 MB 739.3 kB/s eta 0:00:15
   ---------- ----------------------------- 3.8/14.9 MB 740.8 kB/s eta 0:00:15
   ---------- ----------------------------- 3.9/14.9 MB 749.8 kB/s eta 0:00:15
   ---------- ----------------------------- 3.9/14.9 MB 749.8 kB/s eta 0:00:15
   ---------- ----------------------------- 4.0/14.9 MB 755.7 kB/s eta 0:00:15
   ----------- ---------------------------- 4.1/14.9 MB 762.6 kB/s eta 0:00:15
   ----------- ---------------------------- 4.2/14.9 MB 769.0 kB/s eta 0:00:14
   ----------- ---------------------------- 4.2/14.9 MB 779.7 kB/s eta 0:00:14
   ----------- ---------------------------- 4.3/14.9 MB 785.7 kB/s eta 0:00:14
   ----------- ---------------------------- 4.5/14.9 MB 801.2 kB/s eta 0:00:13
   ------------ --------------------------- 4.5/14.9 MB 806.4 kB/s eta 0:00:13
   ------------ --------------------------- 4.5/14.9 MB 803.3 kB/s eta 0:00:13
   ------------ --------------------------- 4.6/14.9 MB 801.3 kB/s eta 0:00:13
   ------------ --------------------------- 4.6/14.9 MB 805.4 kB/s eta 0:00:13
   ------------ --------------------------- 4.7/14.9 MB 818.7 kB/s eta 0:00:13
   ------------- -------------------------- 4.8/14.9 MB 831.6 kB/s eta 0:00:13
   ------------- -------------------------- 5.0/14.9 MB 844.2 kB/s eta 0:00:12
   ------------- -------------------------- 5.1/14.9 MB 859.4 kB/s eta 0:00:12
   -------------- ------------------------- 5.2/14.9 MB 872.1 kB/s eta 0:00:12
   -------------- ------------------------- 5.3/14.9 MB 880.0 kB/s eta 0:00:11
   -------------- ------------------------- 5.4/14.9 MB 890.2 kB/s eta 0:00:11
   -------------- ------------------------- 5.5/14.9 MB 899.0 kB/s eta 0:00:11
   --------------- ------------------------ 5.6/14.9 MB 913.2 kB/s eta 0:00:11
   --------------- ------------------------ 5.7/14.9 MB 918.6 kB/s eta 0:00:10
   --------------- ------------------------ 5.9/14.9 MB 935.5 kB/s eta 0:00:10
   --------------- ------------------------ 5.9/14.9 MB 938.3 kB/s eta 0:00:10
   ---------------- ----------------------- 6.0/14.9 MB 946.6 kB/s eta 0:00:10
   ---------------- ----------------------- 6.1/14.9 MB 961.4 kB/s eta 0:00:10
   ---------------- ----------------------- 6.3/14.9 MB 973.6 kB/s eta 0:00:09
   ----------------- ---------------------- 6.4/14.9 MB 984.6 kB/s eta 0:00:09
   ----------------- ---------------------- 6.5/14.9 MB 993.2 kB/s eta 0:00:09
   ----------------- ---------------------- 6.6/14.9 MB 1.0 MB/s eta 0:00:09
   ------------------ --------------------- 6.7/14.9 MB 1.0 MB/s eta 0:00:09
   ------------------ --------------------- 6.9/14.9 MB 1.0 MB/s eta 0:00:08
   ------------------ --------------------- 7.0/14.9 MB 1.0 MB/s eta 0:00:08
   ------------------- -------------------- 7.1/14.9 MB 1.1 MB/s eta 0:00:08
   ------------------- -------------------- 7.3/14.9 MB 1.1 MB/s eta 0:00:08
   ------------------- -------------------- 7.4/14.9 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 7.6/14.9 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 7.6/14.9 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 7.7/14.9 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 7.8/14.9 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 7.8/14.9 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 7.9/14.9 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 8.0/14.9 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 8.0/14.9 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 8.1/14.9 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 8.1/14.9 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 8.2/14.9 MB 1.1 MB/s eta 0:00:07
   ---------------------- ----------------- 8.3/14.9 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 8.3/14.9 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 8.4/14.9 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 8.4/14.9 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 8.4/14.9 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 8.5/14.9 MB 1.1 MB/s eta 0:00:06
   ----------------------- ---------------- 8.6/14.9 MB 1.1 MB/s eta 0:00:06
   ----------------------- ---------------- 8.6/14.9 MB 1.1 MB/s eta 0:00:06
   ----------------------- ---------------- 8.7/14.9 MB 1.1 MB/s eta 0:00:06
   ----------------------- ---------------- 8.8/14.9 MB 1.1 MB/s eta 0:00:06
   ----------------------- ---------------- 8.8/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 8.9/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 8.9/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.0/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.0/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.0/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.0/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.0/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.0/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.1/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.1/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.1/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.1/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.1/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.1/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.1/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.2/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.2/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.2/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.2/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.2/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.2/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.2/14.9 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.3/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------ --------------- 9.3/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 9.3/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 9.3/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 9.3/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 9.3/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 9.4/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 9.4/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 9.4/14.9 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 9.5/14.9 MB 1.0 MB/s eta 0:00:06

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## 🔑 Registro y Conexión

Para habilitar el acceso a los datos de la plataforma de Google, es necesario seguir un proceso de configuración en la consola de desarrolladores:

1.  **Registro y Proyecto:** Crear un nuevo proyecto en [Google Cloud Console](https://console.cloud.google.com).
2.  **Habilitar Servicios:** Añadir los servicios específicos que se van a consumir (en este caso, **YouTube Data API v3**).
3.  **Credenciales:** Generar una **API Key** exclusiva para el proyecto, la cual debe almacenarse de forma segura.

### 💻 Configuración del Acceso
Una vez obtenida la clave, la almacenamos en una constante y configuramos el objeto de servicio para realizar las peticiones:

```python
from googleapiclient.discovery import build

# Definición de credenciales y servicio
API_KEY = "TU_API_KEY_AQUI"


# Creación de la instancia de conexión
youtube = build(YOUTUBE_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=API_KEY)

In [3]:
from googleapiclient.discovery import build
import pandas as pd

# Sustituye con tu clave de API obtenida en Google Cloud Console
API_KEY = 'AIzaSyB_xu95PAzpiMUDQyIeTmx7WXmbcCs9WgM'
YOUTUBE_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
youtube = build(YOUTUBE_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=API_KEY)

PERFILES = {
    'carpinteria': {'edad_media': 40, 'sexo_h': 0.92, 'sexo_m': 0.08},
    'bricolaje': {'edad_media': 30, 'sexo_h': 0.54, 'sexo_m': 0.46}
}

In [4]:
#definimos la función para buscar videos en YouTube de ejemplo sobre carpintería o bricolaje
def buscar_videos_youtube(query, max_results=10):
    # 1. Búsqueda inicial para obtener IDs de videos
    search_request = youtube.search().list(
        q=query,
        part='snippet',
        type='video',
        maxResults=max_results,
        order='viewCount'
    )
    search_response = search_request.execute()
    
    video_ids = [item['id']['videoId'] for item in search_response['items']]
    
    # 2. Consulta detallada de estadísticas de esos IDs
    stats_request = youtube.videos().list(
        part='snippet,statistics',
        id=','.join(video_ids)
    )
    stats_response = stats_request.execute()
    
    
    # 3. Procesamiento de los datos para la tabla
    datos = []
    for video in stats_response['items']:
        datos.append({
            'Título': video['snippet']['title'],
            'Canal': video['snippet'],
            'Vistas': int(video['statistics'].get('viewCount', 0)),
            'Likes': int(video['statistics'].get('likeCount', 0)),
            'Publicado': video['snippet']['publishedAt'],
            'Link': f"https://www.youtube.com/watch?v={video['id']}"
        })
    
    return pd.DataFrame(datos)

In [5]:
buscar_videos_youtube("carpintería madera", max_results=5)

,Título,Canal,Vistas,Likes,Publicado,Link
0,Impresionante idea para usar martillo en la ca...,"{'publishedAt': '2025-09-02T20:37:33Z', 'chann...",24951548,188582,2025-09-02T20:37:33Z,https://www.youtube.com/watch?v=niTUI5D_X8c
1,1 Month in 10 Minutes! This Skillful Man Build...,"{'publishedAt': '2021-11-17T15:25:18Z', 'chann...",12581760,167510,2021-11-17T15:25:18Z,https://www.youtube.com/watch?v=mHIe9VSikbA
2,Sin clavos ni tornillos: El secreto de la carp...,"{'publishedAt': '2024-12-14T19:07:29Z', 'chann...",12101912,666180,2024-12-14T19:07:29Z,https://www.youtube.com/watch?v=P09aUgb0kyA
3,Cama de Madera Moderna Muy Fácil De hacer - Tu...,"{'publishedAt': '2021-02-20T19:30:04Z', 'chann...",9676660,151203,2021-02-20T19:30:04Z,https://www.youtube.com/watch?v=Z2rV5DlGyz0
4,Así es la Carpintería japonesa 😱#shorts,"{'publishedAt': '2024-03-09T03:41:44Z', 'chann...",10343537,488438,2024-03-09T03:41:44Z,https://www.youtube.com/watch?v=nryG2QDOktw

## 📂 Listado de Categorías y Limitaciones

En esta fase, procedemos a listar las categorías principales que ofrece la API de YouTube para clasificar el contenido. Es aquí donde identificamos el **primer obstáculo técnico** del análisis:

### ⚠️ El Problema de la Segmentación
YouTube utiliza un sistema de categorías predefinido (*Video Categories*) que presenta las siguientes limitaciones:

*   **Alcance Genérico:** Solo existen aproximadamente **30 categorías principales**.
*   **Falta de Especificidad:** Estas áreas son muy generales (ej. *Entertainment*, *Howto & Style*, *Education*).
*   **Sectorización Limitada:** No existe una categoría nativa específica para **"Bricolaje"** o **"Carpintería"**, lo que obliga a replantear la estrategia de búsqueda mediante *keywords* o etiquetas en lugar de ID de categoría.

> [!IMPORTANT]
> Debido a esta restricción, la segmentación del estudio deberá apoyarse en el filtrado por **términos de búsqueda (queries)** y no solo en los metadatos de categoría de la API.

In [25]:
def listar_categorias_por_region(region='ES'):
    # Llamada al endpoint videoCategories
    request = youtube.videoCategories().list(
        part='snippet',
        regionCode=region
    )
    response = request.execute()
    
    # Procesar los resultados en una lista de diccionarios
    categorias_lista = []
    for item in response.get('items',):
        categorias_lista.append({
            'ID_Categoria': item['id'],
            'Nombre': item['snippet']['title'],
            'Asignable': item['snippet']['assignable'] # Indica si es usable para nuevos videos
        })
    
    return pd.DataFrame(categorias_lista)

# Ejemplo: Listar categorías disponibles en España
df_categorias = listar_categorias_por_region('UK')
df_categorias

   ID_Categoria                Nombre  Asignable
0             1      Film & Animation       True
1             2      Autos & Vehicles       True
2            10                 Music       True
3            15        Pets & Animals       True
4            17                Sports       True
5            18          Short Movies      False
6            19       Travel & Events       True
7            20                Gaming       True
8            21         Videoblogging      False
9            22        People & Blogs       True
10           23                Comedy       True
11           24         Entertainment       True
12           25       News & Politics       True
13           26         Howto & Style       True
14           27             Education       True
15           28  Science & Technology       True
16           30                Movies      False
17           31       Anime/Animation      False
18           32      Action/Adventure      False
19           33              Classics      False
20           34                Comedy      False
21           35           Documentary      False
22           36                 Drama      False
23           37                Family      False
24           38               Foreign      False
25           39                Horror      False
26           40        Sci-Fi/Fantasy      False
27           41              Thriller      False
28           42                Shorts      False
29           43                 Shows      False
30           44              Trailers      False

In [11]:
def generar_dataset_herramientas(termino, max_vids=50):
    # Búsqueda restringida: solo videos, categoría Howto y Style (26)
    search_response = youtube.search().list(
        q=termino,
        part='snippet',
        type='video',
        videoCategoryId="26", 
        maxResults=max_vids,
        order='viewCount'
    ).execute()

    video_ids = [item['id']['videoId'] for item in search_response['items']]
    
    # Obtención de estadísticas (reproducciones)
    stats_response = youtube.videos().list(
        part='snippet,statistics',
        id=','.join(video_ids)
    ).execute()

    lista_final = []
    for vid in stats_response['items']:
        title = vid['snippet']['title'].lower()
        views = int(vid['statistics'].get('viewCount', 0))
        
        # Lógica de sectorización para asignar demografía
        if 'carpinteria' in title or 'woodworking' in title or 'madera' in title:
            perfil = PERFILES['carpinteria']
            tag = 'Carpintería'
        else:
            perfil = PERFILES['bricolaje']
            tag = 'Bricolaje/DIY'

        lista_final.append({
            'Título': vid['snippet']['title'],
            'Temática': tag,
            'Vistas': views,
            'Edad_Media_Est': perfil['edad_media'],
            'Prob_Hombre': perfil['sexo_h'],
            'Prob_Mujer': perfil['sexo_m'],
            'Fecha_Pub': vid['snippet']['publishedAt']
        })
    
    return pd.DataFrame(lista_final)

In [16]:
# Buscamos términos específicos del sector
query = "carpintería madera | bricolaje herramientas | woodworking techniques"
df_tools = generar_dataset_herramientas(query, max_vids=30)

# Mostramos los videos con más reproducciones y su demografía estimada
df_tools.sort_values(by='Vistas', ascending=False).head(10)

,Título,Temática,Vistas,Edad_Media_Est,Prob_Hombre,Prob_Mujer,Fecha_Pub
0,Hand tool joinery #woodworking #tools #joiner...,Carpintería,34375902,40,0.92,0.08,2023-08-16T13:33:55Z
4,Impresionante idea para usar martillo en la ca...,Carpintería,24951233,40,0.92,0.08,2025-09-02T20:37:33Z
1,Secret Wooden Key & Lock. Simple DIY #woodwor...,Carpintería,24441797,40,0.92,0.08,2024-06-01T17:01:33Z
2,34 Ingenious Intelligent Secrets & Tips That W...,Carpintería,20526252,40,0.92,0.08,2023-01-27T08:25:36Z
3,7 Simple Woodworking Tools Hacks | woodworking...,Carpintería,16382499,40,0.92,0.08,2023-01-08T06:25:54Z
5,I Turned an Osage Orange Log into a Wooden Mal...,Bricolaje/DIY,13358420,30,0.54,0.46,2022-09-12T15:10:02Z
14,truco del carpintero japonés mas famoso de int...,Carpintería,10458433,40,0.92,0.08,2025-12-04T02:59:00Z
7,How do you Know your Edge is Sharp? #woodwork ...,Carpintería,9126154,40,0.92,0.08,2024-11-04T17:00:45Z
6,TOP100 Woodworking Tools Hacks | Woodworking I...,Carpintería,9090107,40,0.92,0.08,2024-09-08T05:27:30Z
13,Easy money! #woodworking #kitchen #kitchentoo...,Carpintería,7602466,40,0.92,0.08,2025-05-09T14:00:09Z

In [6]:
searchs = pd.read_csv(".\\searched_with_top-queries_ES_20210322-2141_20260322-2141.csv")
searchs.head(20)

               query  search interest increase percent
0          paper diy              100            300 %
1          diy paper               93            300 %
2          ideas diy               73            -40 %
3          diy ideas               72            -40 %
4        diy crochet               58            190 %
5         diy crafts               57             60 %
6           diy home               56             70 %
7   manualidades diy               54            -60 %
8   diy manualidades               54            -60 %
9       manualidades               53            -60 %
10         diy house               47             30 %
11           diy bag               46            120 %
12         papel diy               43             30 %
13          easy diy               40             20 %
14           diy box               40             20 %
15         diy decor               40            -60 %
16     christmas diy               37             10 %
17     diy christmas               37             10 %
18       diy navidad               37            -30 %
19      diy projects               34            200 %